services:
  - type: web
    name: employee-directory
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    pullRequestPreviewsEnabled: true
    envVars:
      - key: VUE_APP_API_URL
        sync: false
    routes:
      - type: rewrite
        source: /*
        destination: /index.html 